---
# Playbook to install proxmox and set up storage
# In theory lae.proxmox could set up a cluster

- name: "Install proxmox using lae.proxmox role"
  hosts: pve
  user: root
  gather_facts: true
  # Most variables should come from the group_vars/pve/01 vars.yml file
  vars:
    pve_group: pve
    interfaces_template: "~/repo/ansible_proxmox_hetzner/roles/lae.proxmox/templates/interfaces-{{ pve_group }}.j2"
    # Bridge for VMs
    vm_bridge_name: vmbr50
    vm_network_lan_subnet: "24"
    vm_network_lan_ip: "10.0.0.1"
    vm_network_vm_lan_ip: "10.0.0.254"
    vm_network_vm_lan_dhcp_from: "10.0.0.50"
    vm_network_vm_lan_dhcp_to: "10.0.0.150"

  # ADD IN DEBIAN FOR MAILCOW INSTALLATION

  tasks:
    - name: Set up zpool tank and vm-drives
      ansible.builtin.include_role:
        name: zfs_filesystem
      vars:
        zfs_filesystem_install_pool: true
        zfs_filesystem_pool_name: tank
        zfs_filesystem_pool_mode: mirror
        zfs_filesystem_pool_devices: "{{ hostvars[inventory_hostname].zfs_tank_devices }}"
        zfs_filesystem_filesystems:
          - name: vm-drives
            mountpath: "/vm-drives"

    - name: Set up zpool rpool and isos and backups
      ansible.builtin.include_role:
        name: zfs_filesystem
      vars:
        zfs_filesystem_install_pool: false
        zfs_filesystem_pool_name: rpool
        zfs_filesystem_filesystems:
          - name: isos
            mountpath: "/isos"
          - name: backups
            mountpath: "/backups"

    - name: Install bridge-utils
      ansible.builtin.apt:
        name: bridge-utils

    - name: Configure /etc/network/interfaces
      ansible.builtin.template:
        src: "{{ interfaces_template }}"
        dest: /etc/network/interfaces
      register: _configure_interfaces

    - name: Reboot for network change
      when: _configure_interfaces is changed
      block:
        - name: Reboot for networking changes
          ansible.builtin.shell: "sleep 5 && shutdown -r now 'Networking changes found, rebooting'"
          async: 1
          poll: 0

        - name: Wait for server to come back online
          ansible.builtin.wait_for_connection:
            delay: 30

    - name: Test lae.proxmox
      ansible.builtin.include_role:
        name: lae.proxmox
      vars:
        - pve_group: pve
        - pve_reboot_on_kernel_update: true
        - pve_repository_line: "deb [arch=amd64] http://mirror.hetzner.com/debian/pve {{ ansible_facts.distribution_release }} pve-no-subscription"
        - pve_storages:
            - name: vm-drives
              type: dir
              content: ["images", "rootdir"]
              path: /tank/vm-drives
            - name: backups
              type: dir
              content: ["backup"]
              path: /backups
            - name: "isos"
              type: dir
              content: ["snippets", "vztmpl", "iso"]
              path: /isos

    # Install sudo apt install libguestfs-tools -y so can adjust images
    - name: Install vm guest tools
      ansible.builtin.apt:
        name: libguestfs-tools
        state: present

    - name: Create a snapshot of rpool
      community.general.zfs:
        name: rpool/ROOT/debian@proxmox_install
        state: present

    - name: Create a snapshot of bpool
      community.general.zfs:
        name: bpool/BOOT/debian@proxmox_install
        state: present
